services:
  db:
    image: postgres
    container_name: ft-postgres
    restart: always
    environment:
      POSTGRES_DB: fast_tasker
      POSTGRES_USER: back_fast_tasker
      POSTGRES_PASSWORD: Fasttaskerbackpassword-123666
    ports:
      - "5433:5432"
    volumes:
      - fasttasker_data:/var/lib/postgresql

volumes:
  fasttasker_data:
