package com.fasttasker.fast_tasker.domain.conversation;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

import java.time.Instant;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class MessageTest {

    private Conversation mockConversation;
    private UUID validSenderId;
    private MessageContent mockMessageContent;

    @BeforeEach
    void setUp() {
        mockConversation = Mockito.mock(Conversation.class);
        validSenderId = UUID.randomUUID();
        mockMessageContent = Mockito.mock(MessageContent.class);
    }

    @Nested
    @DisplayName("Constructor Tests")
    class ConstructorTests {

        @Test
        void shouldCreateMessageSuccessfully() {
            Message message = new Message(mockConversation, validSenderId, mockMessageContent);

            assertThat(message).isNotNull();
            assertThat(message.getId()).isNotNull(); // ID should be generated by JPA, but for domain object it's fine to be null initially or generated by builder
            assertThat(message.getConversation()).isEqualTo(mockConversation);
            assertThat(message.getSenderId()).isEqualTo(validSenderId);
            assertThat(message.getContent()).isEqualTo(mockMessageContent);
            assertThat(message.getSentAt()).isNotNull();
            assertThat(message.getReadAt()).isNull();
        }

        @Test
        void shouldThrowWhenConversationIsNull() {
            assertThatThrownBy(() -> new Message(null, validSenderId, mockMessageContent))
                    .isInstanceOf(IllegalArgumentException.class)
                    .hasMessage("conversation cannot be null");
        }

        @Test
        void shouldThrowWhenSenderIdIsNull() {
            assertThatThrownBy(() -> new Message(mockConversation, null, mockMessageContent))
                    .isInstanceOf(IllegalArgumentException.class)
                    .hasMessage("senderId cannot be null");
        }

        @Test
        void shouldThrowWhenContentIsNull() {
            assertThatThrownBy(() -> new Message(mockConversation, validSenderId, null))
                    .isInstanceOf(IllegalArgumentException.class)
                    .hasMessage("content cannot be null");
        }
    }

    @Nested
    @DisplayName("Business Method Tests")
    class BusinessMethodTests {

        private Message message;

        @BeforeEach
        void init() {
            message = new Message(mockConversation, validSenderId, mockMessageContent);
        }

        @Test
        void shouldMarkAsReadSuccessfullyWhenNotRead() {
            assertThat(message.isRead()).isFalse();
            message.markAsRead();
            assertThat(message.isRead()).isTrue();
            assertThat(message.getReadAt()).isNotNull();
        }

        @Test
        void shouldNotChangeReadAtIfAlreadyRead() {
            Instant initialReadAt = Instant.now().minusSeconds(60);
            message.setReadAt(initialReadAt); // Simulate already read

            message.markAsRead();

            assertThat(message.getReadAt()).isEqualTo(initialReadAt);
        }

        @Test
        void isReadShouldReturnTrueWhenReadAtIsSet() {
            message.markAsRead();
            assertThat(message.isRead()).isTrue();
        }

        @Test
        void isReadShouldReturnFalseWhenReadAtIsNull() {
            assertThat(message.getReadAt()).isNull();
            assertThat(message.isRead()).isFalse();
        }
    }
}